# Generated by Django 5.0.7 on 2024-08-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
