# Generated by Django 5.0.7 on 2024-08-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user',
            new_name='user_id',
        ),
    ]
