# Generated by Django 5.0.7 on 2024-08-27 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_remove_workout_user_id_workout_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
